name: Deploy to Render

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test --if-present

      - name: Build project
        run: npm run build

      - name: Deploy to Render
        run: |
          # Chọn service ID dựa theo nhánh
          SERVICE_ID=$([ "${GITHUB_REF##*/}" = "main" ] && echo "${{ secrets.RENDER_SERVICE_ID_PROD }}" || echo "${{ secrets.RENDER_SERVICE_ID_STAGING }}")
          echo "Deploying to service ID: $SERVICE_ID"
          curl -X POST "https://api.render.com/v1/services/$SERVICE_ID/deploys" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Accept: application/json"
